url=jdbc:mysql://localhost:3306/SEUDB
usuario=SEU_USUARIO
senha=SUA_SENHA



=====database.example.properties+=======

Obrigatorio fazer para ter os dados inseridos no console do intellij no MySQL